### ISSUE TITLE
Gists from files and replies

### ISSUE THREAD

**Issue by xFGhoul** [FalseDev/Tech-Struck#18]
When an attachment(s) is sent with the `create gist` command it will be created into a gist

**Comment by CodeWithSwastik** [comment]
You can make it paste it into a pastebin if they don't have their github logged in

**Comment by FalseDev** [comment]
### Finalized implementation details:
#### Ways to create gist
 - Reply to a message with file attachments
 - Send attachments in the command message
 - Using the current syntax

The command should check all three things, and combine all of the attachments and in message files

#### Checks
 - Max size allowed per file is 20kb
 - File must be text, otherwise `.encode("utf-8")` will fail trying to convert binaries, catch the error and inform the user
 - Use the filenames in discord as the filename in the gist as well

**Comment by CaffeineDuck** [comment]
> ### Finalized implementation details:
> #### Ways to create gist
> * Reply to a message with file attachments
> * Send attachments in the command message
> * Using the current syntax
> 
> The command should check all three things, and combine all of the attachments and in message files
> 
> #### Checks
> * Max size allowed per file is 20kb
> * File must be text, otherwise `.encode("utf-8")` will fail trying to convert binaries, catch the error and inform the user
> * Use the filenames in discord as the filename in the gist as well

Ok, will work on it.

**Comment by FalseDev** [comment]
This feature has been added in commit e5224bd22ec2178c3d48017ed2efbb6aa763b7a2
